export interface SeedDataset {
  tenants: any[];
  users: any[];
  vehicles: any[];
  drivers: any[];
  trips: any[];
  bookings: any[];
  invoices: any[];
  ledgerEntries: any[];
  exceptions: any[];
  approvals: any[];
  whatsappMessages: any[];
  liveLocations: any[];
}

export const initialSeedData: SeedDataset = {
  tenants: [
    {
      id: 'tenant_delhi_01',
      name: 'Marichi Logistics Pvt Ltd',
      gstin: '07AAAAA0000A1Z5',
      pan: 'AAAAA0000A',
      stateCode: '07',
      registeredAddress: 'Plot 42, Okhla Industrial Area Phase III, New Delhi 110020',
      branches: [
        { code: 'DL-Okhla', name: 'Delhi NCR Central Hub', gstin: '07AAAAA0000A1Z5' },
        { code: 'MH-Bhiwandi', name: 'Mumbai Bhiwandi Logistics Park', gstin: '27AAAAA0000A1Z2' },
        { code: 'KA-Peenya', name: 'Bengaluru Peenya Hub', gstin: '29AAAAA0000A1ZY' },
      ],
      createdAt: new Date().toISOString(),
    },
  ],

  users: [
    {
      id: 'usr_owner_01',
      tenantId: 'tenant_delhi_01',
      name: 'Rajesh Sharma',
      email: 'owner@marichifleet.com',
      role: 'FLEET_OWNER',
      branches: ['DL-Okhla', 'MH-Bhiwandi', 'KA-Peenya'],
      phone: '+91 98111 00001',
    },
    {
      id: 'usr_disp_01',
      tenantId: 'tenant_delhi_01',
      name: 'Amit Verma',
      email: 'dispatcher@marichifleet.com',
      role: 'DISPATCHER',
      branches: ['DL-Okhla'],
      phone: '+91 98111 00002',
    },
    {
      id: 'usr_tower_01',
      tenantId: 'tenant_delhi_01',
      name: 'Sunil Yadav',
      email: 'tower@marichifleet.com',
      role: 'CONTROL_TOWER_LEAD',
      branches: ['DL-Okhla', 'MH-Bhiwandi', 'KA-Peenya'],
      phone: '+91 98111 00003',
    },
    {
      id: 'usr_fin_01',
      tenantId: 'tenant_delhi_01',
      name: 'Pooja Mehra',
      email: 'finance@marichifleet.com',
      role: 'FINANCE_CONTROLLER',
      branches: ['DL-Okhla'],
      phone: '+91 98111 00004',
    },
    {
      id: 'usr_driver_01',
      tenantId: 'tenant_delhi_01',
      name: 'Ramesh Kumar',
      email: 'ramesh.driver@marichifleet.com',
      role: 'DRIVER',
      branches: ['DL-Okhla'],
      phone: '+91 98110 23456',
    },
  ],

  vehicles: [
    {
      id: 'veh_01',
      tenantId: 'tenant_delhi_01',
      regNumber: 'NL01AC2849',
      model: 'Tata Prima 5530.S (55T Multi-Axle)',
      capacityTons: 55,
      type: 'TRAILER_FLATBED',
      status: 'IN_TRANSIT',
      currentLocation: {
        latitude: 26.9124,
        longitude: 75.7873,
        address: 'NH-48 Near Jaipur Bypass, Rajasthan',
        speedKmH: 62,
        bearing: 215,
        updatedAt: new Date().toISOString(),
      },
      fuelLevelPercent: 78,
      batteryVolts: 24.6,
      odometerKm: 142580,
      assignedDriverId: 'drv_01',
      currentTripId: 'TRP-2026-00891',
      documents: {
        rcValidUntil: '2028-04-15',
        fitnessValidUntil: '2027-02-28',
        insuranceValidUntil: '2026-11-30',
        pucValidUntil: '2026-08-20',
      },
    },
    {
      id: 'veh_02',
      tenantId: 'tenant_delhi_01',
      regNumber: 'MH04JK8921',
      model: 'BharatBenz 2823C (28T Heavy Tipper)',
      capacityTons: 28,
      type: 'CONTAINER_CLOSED',
      status: 'AT_LOADING',
      currentLocation: {
        latitude: 18.9498,
        longitude: 72.9525,
        address: 'JNPT Port Gate 3, Navi Mumbai, Maharashtra',
        speedKmH: 0,
        bearing: 90,
        updatedAt: new Date().toISOString(),
      },
      fuelLevelPercent: 92,
      batteryVolts: 24.2,
      odometerKm: 68240,
      assignedDriverId: 'drv_02',
      currentTripId: 'TRP-2026-00892',
      documents: {
        rcValidUntil: '2029-01-10',
        fitnessValidUntil: '2027-06-15',
        insuranceValidUntil: '2027-01-05',
        pucValidUntil: '2026-09-12',
      },
    },
    {
      id: 'veh_03',
      tenantId: 'tenant_delhi_01',
      regNumber: 'KA01MJ4401',
      model: 'Volvo FH16 (40T Reefer Cold-Chain)',
      capacityTons: 40,
      type: 'REEFER',
      status: 'IN_TRANSIT',
      currentLocation: {
        latitude: 14.4426,
        longitude: 75.9212,
        address: 'NH-48 Davanagere stretch, Karnataka',
        speedKmH: 74,
        bearing: 340,
        updatedAt: new Date().toISOString(),
      },
      fuelLevelPercent: 65,
      batteryVolts: 24.8,
      reeferTempCelsius: -18.2,
      odometerKm: 89410,
      assignedDriverId: 'drv_03',
      currentTripId: 'TRP-2026-00893',
      documents: {
        rcValidUntil: '2030-08-22',
        fitnessValidUntil: '2027-10-30',
        insuranceValidUntil: '2026-12-14',
        pucValidUntil: '2026-10-01',
      },
    },
    {
      id: 'veh_04',
      tenantId: 'tenant_delhi_01',
      regNumber: 'HR38AB5512',
      model: 'Ashok Leyland 4220 (42T Haulage)',
      capacityTons: 42,
      type: 'HAULAGE_OPEN',
      status: 'AVAILABLE',
      currentLocation: {
        latitude: 28.5355,
        longitude: 77.2731,
        address: 'Marichi Central Yard, Okhla Ph-III, Delhi',
        speedKmH: 0,
        bearing: 0,
        updatedAt: new Date().toISOString(),
      },
      fuelLevelPercent: 88,
      batteryVolts: 24.5,
      odometerKm: 198300,
      assignedDriverId: null,
      currentTripId: null,
      documents: {
        rcValidUntil: '2027-09-19',
        fitnessValidUntil: '2026-12-31',
        insuranceValidUntil: '2026-10-18',
        pucValidUntil: '2026-07-25',
      },
    },
    {
      id: 'veh_05',
      tenantId: 'tenant_delhi_01',
      regNumber: 'DL1AA9923',
      model: 'Eicher Pro 3019 (19T Express Container)',
      capacityTons: 19,
      type: 'CONTAINER_CLOSED',
      status: 'MAINTENANCE',
      currentLocation: {
        latitude: 28.5245,
        longitude: 77.2801,
        address: 'Authorized Eicher Workshop, Badarpur Border, Delhi',
        speedKmH: 0,
        bearing: 0,
        updatedAt: new Date().toISOString(),
      },
      fuelLevelPercent: 35,
      batteryVolts: 23.9,
      odometerKm: 112450,
      assignedDriverId: null,
      currentTripId: null,
      documents: {
        rcValidUntil: '2028-11-11',
        fitnessValidUntil: '2027-03-20',
        insuranceValidUntil: '2026-10-05',
        pucValidUntil: '2026-08-30',
      },
    },
  ],

  drivers: [
    {
      id: 'drv_01',
      tenantId: 'tenant_delhi_01',
      name: 'Ramesh Kumar',
      phone: '+91 98110 23456',
      licenseNumber: 'DL-0420180029381',
      licenseValidUntil: '2031-06-15',
      status: 'ON_TRIP',
      currentTripId: 'TRP-2026-00891',
      rating: 4.85,
      totalTripsCompleted: 142,
      aadhaarLast4: '8839',
      settlementPendingAmount: 4200,
    },
    {
      id: 'drv_02',
      tenantId: 'tenant_delhi_01',
      name: 'Satnam Singh',
      phone: '+91 98765 43210',
      licenseNumber: 'PB-1020150019283',
      licenseValidUntil: '2029-11-20',
      status: 'ON_TRIP',
      currentTripId: 'TRP-2026-00892',
      rating: 4.92,
      totalTripsCompleted: 210,
      aadhaarLast4: '4190',
      settlementPendingAmount: 1850,
    },
    {
      id: 'drv_03',
      tenantId: 'tenant_delhi_01',
      name: 'Mahesh Rawat',
      phone: '+91 97112 88392',
      licenseNumber: 'HR-2620190038491',
      licenseValidUntil: '2032-02-10',
      status: 'ON_TRIP',
      currentTripId: 'TRP-2026-00893',
      rating: 4.68,
      totalTripsCompleted: 88,
      aadhaarLast4: '1092',
      settlementPendingAmount: 3100,
    },
  ],

  trips: [
    {
      id: 'TRP-2026-00891',
      tenantId: 'tenant_delhi_01',
      bookingId: 'BKG-10492',
      clientName: 'Reliance Retail Ltd',
      origin: 'Delhi Okhla Hub (DL)',
      destination: 'Mumbai Bhiwandi Logistics Park (MH)',
      vehicleRegNumber: 'NL01AC2849',
      driverId: 'drv_01',
      driverName: 'Ramesh Kumar',
      driverPhone: '+91 98110 23456',
      cargoDescription: 'FMCG Goods & Ambient Retail Pallets',
      weightTons: 28.5,
      totalDistanceKm: 1420,
      completedDistanceKm: 910,
      status: 'IN_TRANSIT',
      slaStatus: 'ON_TIME',
      eta: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
      dispatchedAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
      freightAmount: 162500,
      advancePaid: 45000,
      detentionAccrued: 0,
      checkpoints: [
        { name: 'Okhla Departure Hub', timestamp: new Date(Date.now() - 26 * 3600 * 1000).toISOString(), status: 'COMPLETED' },
        { name: 'Jaipur Toll Plaza (RJ)', timestamp: new Date(Date.now() - 18 * 3600 * 1000).toISOString(), status: 'COMPLETED' },
        { name: 'Udaipur Checkpost (RJ)', timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(), status: 'COMPLETED' },
        { name: 'Vadodara Ring Road (GJ)', timestamp: new Date(Date.now() + 6 * 3600 * 1000).toISOString(), status: 'PENDING' },
        { name: 'Bhiwandi Central Dock (MH)', timestamp: new Date(Date.now() + 18 * 3600 * 1000).toISOString(), status: 'PENDING' },
      ],
      ewayBillNumber: '171092839182',
      ewayBillValidUntil: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    },
    {
      id: 'TRP-2026-00892',
      tenantId: 'tenant_delhi_01',
      bookingId: 'BKG-10493',
      clientName: 'Tata Motors Component Logistics',
      origin: 'Mumbai JNPT Port (MH)',
      destination: 'Pune Chakan Plant Phase-2 (MH)',
      vehicleRegNumber: 'MH04JK8921',
      driverId: 'drv_02',
      driverName: 'Satnam Singh',
      driverPhone: '+91 98765 43210',
      cargoDescription: 'Precision Engine Castings',
      weightTons: 22.0,
      totalDistanceKm: 140,
      completedDistanceKm: 0,
      status: 'AT_LOADING',
      slaStatus: 'RISK',
      eta: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
      dispatchedAt: null,
      freightAmount: 38000,
      advancePaid: 10000,
      detentionAccrued: 1500,
      checkpoints: [
        { name: 'JNPT Port Gate 3', timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), status: 'IN_PROGRESS' },
        { name: 'Khopoli Expressway Exit', timestamp: null, status: 'PENDING' },
        { name: 'Chakan Tata Factory Gate', timestamp: null, status: 'PENDING' },
      ],
      ewayBillNumber: '181290384910',
      ewayBillValidUntil: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    },
    {
      id: 'TRP-2026-00893',
      tenantId: 'tenant_delhi_01',
      bookingId: 'BKG-10494',
      clientName: 'Sun Pharma Specialities',
      origin: 'Bengaluru Peenya Hub (KA)',
      destination: 'Hyderabad Patancheru Pharma City (TG)',
      vehicleRegNumber: 'KA01MJ4401',
      driverId: 'drv_03',
      driverName: 'Mahesh Rawat',
      driverPhone: '+91 97112 88392',
      cargoDescription: 'Temperature-Sensitive Vaccines (-20C)',
      weightTons: 16.5,
      totalDistanceKm: 570,
      completedDistanceKm: 310,
      status: 'IN_TRANSIT',
      slaStatus: 'ON_TIME',
      eta: new Date(Date.now() + 7 * 3600 * 1000).toISOString(),
      dispatchedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
      freightAmount: 94000,
      advancePaid: 25000,
      detentionAccrued: 0,
      checkpoints: [
        { name: 'Peenya Reefer Dock', timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(), status: 'COMPLETED' },
        { name: 'Anantapur Toll (AP)', timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(), status: 'COMPLETED' },
        { name: 'Kurnool Bypass (AP)', timestamp: new Date(Date.now() + 3 * 3600 * 1000).toISOString(), status: 'PENDING' },
        { name: 'Patancheru Receiving Warehouse (TG)', timestamp: new Date(Date.now() + 7 * 3600 * 1000).toISOString(), status: 'PENDING' },
      ],
      ewayBillNumber: '191029384729',
      ewayBillValidUntil: new Date(Date.now() + 36 * 3600 * 1000).toISOString(),
    },
  ],

  bookings: [
    {
      id: 'BKG-10492',
      tenantId: 'tenant_delhi_01',
      clientName: 'Reliance Retail Ltd',
      status: 'CONFIRMED',
      pickupLocation: 'Delhi Okhla Hub',
      deliveryLocation: 'Mumbai Bhiwandi Hub',
      expectedWeightTons: 28.5,
      vehicleTypeRequired: 'TRAILER_FLATBED',
      quotedRate: 162500,
      createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    },
    {
      id: 'BKG-10493',
      tenantId: 'tenant_delhi_01',
      clientName: 'Tata Motors Component Logistics',
      status: 'CONFIRMED',
      pickupLocation: 'Mumbai JNPT Port',
      deliveryLocation: 'Pune Chakan Plant',
      expectedWeightTons: 22.0,
      vehicleTypeRequired: 'CONTAINER_CLOSED',
      quotedRate: 38000,
      createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    },
    {
      id: 'BKG-10495',
      tenantId: 'tenant_delhi_01',
      clientName: 'Amul Gujarat Co-op Milk',
      status: 'REQUESTED',
      pickupLocation: 'Anand (GJ)',
      deliveryLocation: 'Delhi (DL)',
      expectedWeightTons: 25.0,
      vehicleTypeRequired: 'REEFER',
      quotedRate: 115000,
      createdAt: new Date().toISOString(),
    },
  ],

  invoices: [
    {
      id: 'INV-2026-0412',
      tenantId: 'tenant_delhi_01',
      tripId: 'TRP-2026-00891',
      clientName: 'Reliance Retail Ltd',
      clientGstin: '27AABCR1234F1Z8',
      sacCode: '996511',
      freightAmount: 162500,
      detentionAmount: 11375,
      taxableAmount: 173875,
      cgstAmount: 4346.88,
      sgstAmount: 4346.88,
      igstAmount: 0,
      totalAmount: 182568.76,
      status: 'FINALISED',
      irn: '4a8f9c12b7e0d3f829a174029bc48109d4726e91f083b4c7d6e5a4b3c2d1e0f9',
      qrCodeData: 'IRN:4a8f9c12b7e0d3f8|GSTIN:07AAAAA0000A1Z5|INV:INV-2026-0412|TOTAL:182568.76',
      issuedDate: new Date(Date.now() - 10 * 86400 * 1000).toISOString(),
      dueDate: new Date(Date.now() + 20 * 86400 * 1000).toISOString(),
      dsoDays: 10,
    },
    {
      id: 'INV-2026-0413',
      tenantId: 'tenant_delhi_01',
      tripId: 'TRP-2026-00870',
      clientName: 'Tata Motors Ltd',
      clientGstin: '27AAACT2727Q1ZW',
      sacCode: '996511',
      freightAmount: 90000,
      detentionAmount: 0,
      taxableAmount: 90000,
      cgstAmount: 2250,
      sgstAmount: 2250,
      igstAmount: 0,
      totalAmount: 94500,
      status: 'PAID',
      irn: '98f7e6d5c4b3a210fedcba0987654321abcdef0123456789abcdef9876543210',
      qrCodeData: 'IRN:98f7e6d5c4b3a210|GSTIN:07AAAAA0000A1Z5|INV:INV-2026-0413|TOTAL:94500',
      issuedDate: new Date(Date.now() - 25 * 86400 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 5 * 86400 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
      dsoDays: 23,
    },
  ],

  ledgerEntries: [
    {
      id: 'led_01',
      tenantId: 'tenant_delhi_01',
      transactionDate: new Date(Date.now() - 10 * 86400 * 1000).toISOString(),
      referenceId: 'INV-2026-0412',
      referenceType: 'INVOICE',
      debitAccount: '1100-Trade-Receivables',
      creditAccount: '4100-Freight-Revenue',
      amount: 173875,
      narration: 'Freight and detention revenue for Trip TRP-2026-00891 (Reliance Retail)',
    },
    {
      id: 'led_02',
      tenantId: 'tenant_delhi_01',
      transactionDate: new Date(Date.now() - 10 * 86400 * 1000).toISOString(),
      referenceId: 'INV-2026-0412',
      referenceType: 'INVOICE',
      debitAccount: '1100-Trade-Receivables',
      creditAccount: '2200-GST-Output-Liability',
      amount: 8693.76,
      narration: 'CGST and SGST output liability 5% on SAC 996511',
    },
    {
      id: 'led_03',
      tenantId: 'tenant_delhi_01',
      transactionDate: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
      referenceId: 'INV-2026-0413',
      referenceType: 'PAYMENT_RECEIVED',
      debitAccount: '1010-HDFC-Bank-Current-A/C',
      creditAccount: '1100-Trade-Receivables',
      amount: 94500,
      narration: 'NEFT remittance received against invoice INV-2026-0413 from Tata Motors',
    },
  ],

  exceptions: [
    {
      id: 'exc_01',
      tenantId: 'tenant_delhi_01',
      tripId: 'TRP-2026-00891',
      vehicleRegNumber: 'NL01AC2849',
      type: 'GEOFENCE_DEVIATION',
      severity: 'HIGH',
      description: 'Vehicle drifted +14 km outside planned NH-48 corridor near Shahpura.',
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      status: 'OPEN',
    },
    {
      id: 'exc_02',
      tenantId: 'tenant_delhi_01',
      tripId: 'TRP-2026-00893',
      vehicleRegNumber: 'KA01MJ4401',
      type: 'TEMPERATURE_EXCURSION',
      severity: 'CRITICAL',
      description: 'Reefer compartment temperature rose to -14.1C (threshold: -18.0C).',
      timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      status: 'INVESTIGATING',
    },
    {
      id: 'exc_03',
      tenantId: 'tenant_delhi_01',
      tripId: 'TRP-2026-00892',
      vehicleRegNumber: 'MH04JK8921',
      type: 'LOADING_DWELL_EXCEEDED',
      severity: 'MEDIUM',
      description: 'Dock dwell time exceeded 4.5 hours at JNPT Port Gate 3.',
      timestamp: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
      status: 'OPEN',
    },
  ],

  approvals: [
    {
      id: 'appr_fuel_01',
      tenantId: 'tenant_delhi_01',
      department: 'FINANCE',
      category: 'FUEL_REFILL',
      title: 'Diesel Refill Bill Verification (WhatsApp OCR)',
      requestedBy: 'Ramesh Kumar (Driver)',
      driverPhone: '+91 98110 23456',
      vehicleRegNumber: 'NL01AC2849',
      tripId: 'TRP-2026-00891',
      amount: 5593.75,
      fuelDetails: {
        pumpName: 'HPCL Highway Oasis, NH-48 Kotputli',
        volumeLitres: 62.5,
        ratePerLitre: 89.5,
        totalAmount: 5593.75,
        slipNumber: 'HP-771029',
        odometerKm: 142640,
        calculatedMileage: '3.8 km/L (Normal 3.6-4.2 km/L)',
        receiptUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
        geoCheckPassed: true,
      },
      reason: 'Mid-trip diesel refill at Kotputli HPCL station. Bill photo uploaded via driver WhatsApp.',
      status: 'PENDING',
      createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    {
      id: 'appr_adv_01',
      tenantId: 'tenant_delhi_01',
      department: 'FINANCE',
      category: 'CASH_ADVANCE',
      title: 'Emergency Fuel & En-route Cash Advance',
      requestedBy: 'Ramesh Kumar (Driver)',
      driverPhone: '+91 98110 23456',
      vehicleRegNumber: 'NL01AC2849',
      tripId: 'TRP-2026-00891',
      amount: 4000,
      reason: 'Driver cash advance for toll & weighbridge expenses. Remaining trip budget: INR 8,500.',
      status: 'PENDING',
      createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    {
      id: 'appr_det_01',
      tenantId: 'tenant_delhi_01',
      department: 'OPERATIONS',
      category: 'DETENTION_WAIVER',
      title: 'Detention Fee Partial Waiver Request (Goodwill)',
      requestedBy: 'Amit Verma (Dispatcher)',
      clientName: 'Reliance Retail Ltd',
      amount: 6500,
      reason: 'Bhiwandi hub dock power outage delayed unload by 12 hours. Client requesting goodwill waiver.',
      status: 'PENDING',
      createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    },
    {
      id: 'appr_maint_01',
      tenantId: 'tenant_delhi_01',
      department: 'OPERATIONS',
      category: 'MAINTENANCE',
      title: 'Workshop Job Card — Clutch Booster Replacement',
      requestedBy: 'Sunil Yadav (Fleet Lead)',
      vehicleRegNumber: 'DL1AA9923',
      amount: 7800,
      reason: 'Clutch booster pressure drop during pre-dispatch fitness check. Authorized Eicher workshop quotation.',
      status: 'PENDING',
      createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    },
    {
      id: 'appr_rate_01',
      tenantId: 'tenant_delhi_01',
      department: 'FINANCE',
      category: 'RATE_OVERRIDE',
      title: 'Express Sunday Dispatch Rate Override',
      requestedBy: 'Amit Verma (Dispatcher)',
      clientName: 'Amul Gujarat Co-op Milk',
      amount: 125000,
      reason: 'Contract rate is INR 115,000; customer agreed to INR 125,000 for guaranteed 24h temperature-controlled transit.',
      status: 'PENDING',
      createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    },
  ],

  whatsappMessages: [
    {
      id: 'msg_01',
      tenantId: 'tenant_delhi_01',
      sender: 'SYSTEM',
      recipient: '+91 98110 23456',
      content: 'NAYA TRIP - TRP-2026-00891. Delhi Okhla -> Mumbai Bhiwandi (1,420 km). Maal: FMCG Goods 28.5T. Gaadi: NL01AC2849. [HAAN, LE LUNGA] [NAHI LE SAKTA]',
      timestamp: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
      type: 'TRIP_OFFER',
    },
    {
      id: 'msg_02',
      tenantId: 'tenant_delhi_01',
      sender: 'DRIVER',
      senderName: 'Ramesh Kumar',
      senderPhone: '+91 98110 23456',
      content: 'HAAN, LE LUNGA',
      timestamp: new Date(Date.now() - 25.9 * 3600 * 1000).toISOString(),
      type: 'TEXT',
    },
    {
      id: 'msg_03',
      tenantId: 'tenant_delhi_01',
      sender: 'SYSTEM',
      recipient: '+91 98110 23456',
      content: 'Theek hai Ramesh bhai. Trip confirm ho gaya. Advance INR 10,000 aapke card me daal diya hai. Kripya nikalte waqt WhatsApp live location share karein.',
      timestamp: new Date(Date.now() - 25.8 * 3600 * 1000).toISOString(),
      type: 'TEXT',
    },
    {
      id: 'msg_04',
      tenantId: 'tenant_delhi_01',
      sender: 'DRIVER',
      senderName: 'Ramesh Kumar',
      senderPhone: '+91 98110 23456',
      content: '📍 Live location shared (8 hours)',
      location: { latitude: 28.5355, longitude: 77.2731, speed: 0 },
      timestamp: new Date(Date.now() - 25.7 * 3600 * 1000).toISOString(),
      type: 'LOCATION',
    },
    {
      id: 'msg_05',
      tenantId: 'tenant_delhi_01',
      sender: 'DRIVER',
      senderName: 'Ramesh Kumar',
      senderPhone: '+91 98110 23456',
      content: 'Bhai Kotputli HPCL par diesel bharwaya hai. Bill ka photo bhej raha hoon.',
      mediaUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
      timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      type: 'IMAGE_BILL',
    },
    {
      id: 'msg_06',
      tenantId: 'tenant_delhi_01',
      sender: 'SYSTEM',
      recipient: '+91 98110 23456',
      content: '🧾 DIESEL BILL PARSED (OCR):\nPump: HPCL Highway Oasis, Kotputli\nQuantity: 62.50 L\nRate: INR 89.50 / L\nTotal: INR 5,593.75\nSlip No: HP-771029\n\nFinance approval ke liye bheja gaya hai. Approval aate hi confirm karenge.',
      timestamp: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
      type: 'TEXT',
    },
  ],

  liveLocations: [
    {
      vehicleRegNumber: 'NL01AC2849',
      driverPhone: '+91 98110 23456',
      driverName: 'Ramesh Kumar',
      latitude: 26.9124,
      longitude: 75.7873,
      speedKmH: 62,
      bearing: 215,
      isLive: true,
      isDropped: false,
      lastPing: new Date().toISOString(),
      source: 'WHATSAPP_LIVE_LOCATION',
    },
  ],
};
